name: "FiveM Resource Watcher"
description: "Watches for changed resources and restarts them"
inputs:
  restartIndividualResources:
    description: "Restart resources individually or restart the whole server"
    required: false
    default: true
    type: boolean
  serverIP:
    description: "IP of the FiveM server"
    required: true
    default: ""
  serverPort:
    description: "Port of the FiveM server"
    required: false
    default: 30120
  rconPassword:
    description: "Password that you have set for rcon"
    required: true
    default: ""
  resourcesFolder:
    description: "Resources folder name"
    required: false
    default: "resources"
  restartServerWhen0Players:
    description: "Restart the server instead when there are no players on the server"
    required: false
    default: false
    type: boolean
  resourcesToIgnore:
    description: "List of resources that you want to ignore separated by spaces and not restart when changes are made to them"
    required: false
    default: ""
    type: string

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.restartIndividualResources }}
    - ${{ inputs.serverIP }}
    - ${{ inputs.serverPort }}
    - ${{ inputs.rconPassword }}
    - ${{ inputs.resourcesFolder }}
    - ${{ inputs.restartServerWhen0Players }}
    - ${{ inputs.resourcesToIgnore }}
